Language = {}
---------------
-- Notifications
---------------
Language.Notifys = {
	-- General
	["NaoTensNecessario"] = "You don't have the necessary.",
	["SemCanaPesca"] = "You don't have a fishingrod.",
	["SoAnoite"] = "We only work between 20:00 and 00:00.",
	["VoltaNoite"] = "Come back here overnight.",
	["Info1"] = "I know of a friend who buys these fish.",
	["Info2"] = "Search for the restaurant: Train Los Santos Dinner.",
	["NadarPescar"] = "You can't swim and fish at the same time..",
	["ForaVeiculo"] = "You need to be out of a vehicle to fish.",
	["PressionaX"] = "Press [X] to stop fishing",
	["LongeCosta"] = "You need to be further from the coast.",
	["AncoraSolta"] = "Anchor successfully released.",
	["LargarAncora"] = "Boat docked successfully.",
	["PescadoSucesso"] = "Successfully caught fish.",
	["SemIscas"] = "You don't have any fishing bait with you",
	["TentarAbrirTesouro"] = "Trying to open the treasure chest..",
	["ChavePartiu"] = "The corroded key broke.",
	["BauAberto"] = "Treasure chest open! Be sure to collect all your treasure!",
	["Cancelado"] = "Canceled.",
	["ParastePesca"] = "You stopped fishing.",
	["AguaNaoProfunda"] = "The water isn't deep enough to fish.",
	["PescaTerminou"] = "You stopped fishing.",
	["NaoTensChave"] = "You don't have the key to open it.",
	["SpawnBloqueado"] = "There is a vehicle blocking the spawn.",
	["CallPolice"] = "Someone saw you and called the police!",
	["SemIsca"] = "You don't have any fishbait.",
	["Help"] = "Welcome, ",
	["Help2"] = "how can i help you?",
	["NearWater"] = "You are not near water.",
	-- Sell illegal fish
	["GolfinhoVendido"] = "Dolphin sold by: $"..Config.PrecoGolfinho,
	["NaoTensGolfinho"] = "You don't have any dolphins to sell.",
	["TubaraoTVendido"] = "Tiger shark sold by: $"..Config.PrecoTubaraoTigre,
	["NaoTensTubaraoT"] = "You don't have any tiger sharks for sale.",
	["TubaraoMVendido"] = "Hammer shark sold by: $"..Config.PrecoTubaraoMartelo,
	["NaoTensTubaraoM"] = "You don't have any hammerhead sharks for sale.",
	["BaleiaVendida"] = "Whale sold by: $"..Config.PrecoBaleia,
	["NaoTensBaleia"] = "You don't have any whales to sell.",
	-- Sell legal fish
	["CavalaVendida"] = "Mackerel sold by: $"..Config.PrecoCavala,
	["NaoTensCavala"] = "You don't have any mackerel to sell.",
	["BacalhauVendido"] = "Cod sold by: $"..Config.PrecoBacalhau,
	["NaoTensBacalhau"] = "You don't have any cod to sell.",
	["RobaloVendido"] = "Bass sold by: $"..Config.PrecoRobalo,
	["NaoTensRobalo"] = "You don't have any bass to sell.",
	["LinguadoVendido"] = "Flounder sold by: $"..Config.PrecoLinguado,
	["NaoTensLinguado"] = "You don't have any flounder to sell.",
	["RaiaVendida"] = "Stingray sold by: $"..Config.PrecoRaia,
	["NaoTensRaia"] = "You don't have any stingray to sell.",
	["SalmaoVendida"] = "Salmon sold by: $"..Config.PrecoSalmao,
	["NaoTensSalmao"] = "You don't have any salmon to sell.",
	["AtumVendida"] = "Tuna fish sold by: $"..Config.PrecoAtum,
	["NaoTensAtum"] = "You don't have any tuna fish to sell.",
	["SardinhaVendida"] = "Sardine sold by: $"..Config.PrecoSardinha,
	["NaoTensSardinha"] = "You don't have sardine fish to sell.",
	["PeixeGatoVendida"] = "Catfish sold by: $"..Config.PrecoPeixeGato,
	["NaoTensPeixeGato"] = "You don't have catfish to sell.",
	["TamborilVendida"] = "Monkfish sold by: $"..Config.PrecoPeixeGato,
	["NaoTensTamboril"] = "You don't have monkfish to sell.",
	-- Cooking
	["SemBacalhau"] = "You don't have cod.",
	["SemCavala"] = "You don't have mackerel.",
	["SemSalmao"] = "You don't have salmon.",
	["SemSardinha"] = "You don't have sardines.",
	-- Progressbar anchor
	["DroppingAnchor"] = "Dropping the anchor...",
	["PullingAnchor"] = "Pulling the anchor...",
	-- Automatic net fish
	["NetFishing"] = "Fishing...",
	["DroppingNet"] = "Laying the fishing net..",
	["NoBoat"] = "You're not on any boat.",
	["AutomaticNet"] = "The net will fish automatically, you can do other things.",
	["NetCorrupted"] = "The net corrupted and you caught nothing.",
}

---------------
-- Menus
---------------
Language.QBMenu = {
	-- General
	["Pescador"] = "[👩‍🏭] Fisherman",
	["PedirCana"] = "[🎣] I want a fishigrod!",
	["PedirRede"] = "[🎣] I want a net!",
	["AbrirLoja"] = "[📦] Open Shop",
	["UpgradeCana"] = "[✅] Evolve my fishigrod!",
	["UpgradeRede"] = "[✅] Evolve my net!",
	["SellFish"] = "[🐠] I want sell fish!",
	["InfoSobrePeixeIlegal"] = "Do you know anything about illegal fish?",
	-- Sell Legal Fish
	["SellHeader"] = "[🍽] Pearl's Seafood Restaurante",
	["VenderCavala"] = "[🐠] Sell Mackerel",
	["PrecoCavala"] = "Current Price: $"..Config.PrecoCavala.." each",
	["VenderBacalhau"] = "[🐠] Sell Cod",
	["PrecoBacalhau"] = "Current Price: $"..Config.PrecoBacalhau.." each",
	["VenderRobalo"] = "[🐠] Sell Bass",
	["PrecoRobalo"] = "Current Price: $"..Config.PrecoRobalo.." each",
	["VenderLinguado"] = "[🐠] Sell Flounder",
	["PrecoLinguado"] = "Current Price: $"..Config.PrecoLinguado.." each",
	["VenderRaia"] = "[🐠] Sell Stingray",
	["PrecoRaia"] = "Current Price: $"..Config.PrecoRaia.." each",
	["VenderSalmao"] = "[🐠] Sell Salmon",
	["PrecoSalmao"] = "Current Price: $"..Config.PrecoSalmao.." each",
	["VenderAtum"] = "[🐠] Sell Tuna Fish",
	["PrecoAtum"] = "Current Price: $"..Config.PrecoAtum.." each",
	["VenderSardinha"] = "[🐠] Sell Sardine",
	["PrecoSardinha"] = "Current Price: $"..Config.PrecoSardinha.." each",
	["VenderPeixeGato"] = "[🐠] Sell Catfish",
	["PrecoPeixeGato"] = "Current Price: $"..Config.PrecoPeixeGato.." each",
	["VenderTamboril"] = "[🐠] Sell Monkfish",
	["PrecoTamboril"] = "Current Price: $"..Config.PrecoTamboril.." each",
	-- Sell Ilegal Fish
	["VenderGolfinho"] = "[🐬] Sell Dolphin",
	["PrecoGolfinho"] = "Current Price: $"..Config.PrecoGolfinho.." each",
	["VenderTubaraoTigre"] = "[🦈] Sell Tiger Shark",
	["PrecoTubaraoTigre"] = "Current Price: $"..Config.PrecoTubaraoTigre.." each",
	["VenderTubaraoMartelo"] = "[🦈] Sell Hammer Shark",
	["PrecoTubaraoMartelo"] = "Current Price: $"..Config.PrecoTubaraoMartelo.." each",
	["VenderBaleia"] = "[🐋] Sell Whale",
	["PrecoBaleia"] = "Current Price: $"..Config.PrecoBaleia.." each",
	["FecharMenu"] = "[❌] Close",
	-- Upgrades
    ["Upgrades"] = "[✅] Upgrade Fishingrod",
    ["UpgradeLevel2"] = "[🎣] Upgrade to level 2",
    ["RequiredLevel2"] = "Required: <br>"..Config.AmountItemNecessario1.."x "..Config.ItemNecessario1Label.."<br>"..Config.AmountItemNecessario2.."x "..Config.ItemNecessario2Label,
    ["UpgradeLevel3"] = "[🎣] Upgrade to level 3",
    ["RequiredLevel3"] = "Required: <br>"..Config.AmountItemNecessario1.."x "..Config.ItemNecessario1Label.."<br>"..Config.AmountItemNecessario2.."x "..Config.ItemNecessario2Label,
    ["UpgradeLevel4"] = "[🎣] Upgrade to level 4",
    ["RequiredLevel4"] = "Required: <br>"..Config.AmountItemNecessario1.."x "..Config.ItemNecessario1Label.."<br>"..Config.AmountItemNecessario2.."x "..Config.ItemNecessario2Label,
    ["UpgradeLevel5"] = "[🎣] Upgrade to level 5",
    ["RequiredLevel5"] = "Required: <br>"..Config.AmountItemNecessario1.."x "..Config.ItemNecessario1Label.."<br>"..Config.AmountItemNecessario2.."x "..Config.ItemNecessario2Label,

    ["UpgradesRede"] = "[✅] Upgrade Net",
    ["UpgradeRedeLevel2"] = "[🎣] Upgrade to level 2",
    ["RequiredRedeLevel2"] = "Required: <br>"..Config.AmountItemNecessarioRede1.."x "..Config.ItemNecessarioRede1Label.."<br>"..Config.AmountItemNecessarioRede2.."x "..Config.ItemNecessarioRede2Label,
    ["UpgradeRedeLevel3"] = "[🎣] Upgrade to level 3",
    ["RequiredRedeLevel3"] = "Required: <br>"..Config.AmountItemNecessarioRede1.."x "..Config.ItemNecessarioRede1Label.."<br>"..Config.AmountItemNecessarioRede2.."x "..Config.ItemNecessarioRede2Label,
    ["UpgradeRedeLevel4"] = "[🎣] Upgrade to level 4",
    ["RequiredRedeLevel4"] = "Required: <br>"..Config.AmountItemNecessarioRede1.."x "..Config.ItemNecessarioRede1Label.."<br>"..Config.AmountItemNecessarioRede2.."x "..Config.ItemNecessarioRede2Label,
    ["UpgradeRedeLevel5"] = "[🎣] Upgrade to level 5",
    ["RequiredRedeLevel5"] = "Required: <br>"..Config.AmountItemNecessarioRede1.."x "..Config.ItemNecessarioRede1Label.."<br>"..Config.AmountItemNecessarioRede2.."x "..Config.ItemNecessarioRede2Label,
    -- Cooking
    ["Campfire"] = "🔥 Campfire",
    ["CozinharBacalhau"] = "[🍳] Cooking cod",
	["CozinharCavala"] 	= "[🍳] Cooking mackerel",
	["CozinharSalmao"] = "[🍳] Cooking salmon",
	["CozinharSardinha"] = "[🍳] Cooking sardines",
	-- Rent Boats
	["RentBoat"] = "[🛶] I need a boat!",
	["DevolverBarco"] = "[🛶] Return boat",
	["LosSantos"] = "[🏢] Los Santos",
	["PaletoBay"] = "[🏘] Paleto Bay",

}

Language.QBTarget = {
	["Fisherman"] = "Talk with the fisherman",
	["IconFisherman"] = "fas fa-fish",
	["Employe"] = "Talk with employee",
	["IconEmploye"] = "fas fa-fish",
	["Employe2"] = "Talk with employee",
	["IconEmploye2"] = "fas fa-fish",
	["Cook"] = "Cook",
	["IconCook"] = "fa-solid fa-cake-candles",
	["Bonfire"] = "Extinguish Bonfire",
	["IconBonfire"] = "fas fa-fire",
}