Config = {}

--[[Config.ChopExtreme = {
	[1] = 'Adder',
	[2] = 'Tezeract',
	[3] = 'Infernus',
	[4] = 'Zentorno',
	[5] = 'Tempesta',
}

Config.ChopHigh = {
	[1] = 'Voltic',
	[2] = 'Tyrus',
	[3] = 'Buffalo',
	[4] = 'Stretch',
	[5] = 'SultanRS',
}

Config.ChopMed = {
	[1] = 'Sentinel',
	[2] = 'Primo',
	[3] = 'MiniVan',
	[4] = 'Granger',
	[5] = 'Dubsta',
}

Config.ChopLow = {
	[1] = 'Buccaneer',
	[2] = 'Akuma',
	[3] = 'Asea',
	[4] = 'Tailgater',
	[5] = 'Dukes',
}]]


-- rarity 1 > 5 normal
-- 6 > 10 rare / super-rare

Config.vehicleList = {
	[1] = { ["name"] = "Sultan", ["modelname"] = "sultan",["rarity"] = 1 },
	[2] = { ["name"] = "Ingot", ["modelname"] = "INGOT",["rarity"] = 1 },
	[3] = { ["name"] = "Surge", ["modelname"] = "SURGE" ,["rarity"] = 1},
	[4] = { ["name"] = "Issi", ["modelname"] = "ISSI2" ,["rarity"] = 1},
	[5] = { ["name"] = "Gresley", ["modelname"] = "GRESLEY",["rarity"] = 1 },
	[6] = { ["name"] = "Pigalle", ["modelname"] = "PIGALLE" ,["rarity"] = 1},
	[7] = { ["name"] = "Sabre Turbo", ["modelname"] = "SABREGT" ,["rarity"] = 1},
	[8] = { ["name"] = "Landstalker", ["modelname"] = "Landstalker" ,["rarity"] = 1},
	[9] = { ["name"] = "Panto", ["modelname"] = "PANTO" ,["rarity"] = 1},
	[10] = { ["name"] = "Super Diamond", ["modelname"] = "superd" ,["rarity"] = 1},
	[11] = { ["name"] = "Massacro", ["modelname"] = "MASSACRO" ,["rarity"] = 1},
	[12] = { ["name"] = "Schafter", ["modelname"] = "schafter2" ,["rarity"] = 1},
	[13] = { ["name"] = "Bullet", ["modelname"] = "BULLET",["rarity"] = 1 },
	[14] = { ["name"] = "Ruiner", ["modelname"] = "RUINER",["rarity"] = 1 },
	[15] = { ["name"] = "Prairie", ["modelname"] = "PRAIRIE" ,["rarity"] = 1},
	[16] = { ["name"] = "Voltic", ["modelname"] = "VOLTIC" ,["rarity"] = 1},
	[17] = { ["name"] = "Sentinel", ["modelname"] = "SENTINEL2" ,["rarity"] = 1},
	[18] = { ["name"] = "Intruder", ["modelname"] = "INTRUDER" ,["rarity"] = 1},
	[19] = { ["name"] = "Seminole", ["modelname"] = "SEMINOLE" ,["rarity"] = 1},
	[20] = { ["name"] = "Felon GT", ["modelname"] = "FELON2" ,["rarity"] = 1},
	[21] = { ["name"] = "Emperor", ["modelname"] = "EMPEROR",["rarity"] = 1 },
	[22] = { ["name"] = "Manana", ["modelname"] = "MANANA",["rarity"] = 1 },
	[23] = { ["name"] = "Coquette", ["modelname"] = "COQUETTE",["rarity"] = 13 },
	[24] = { ["name"] = "9F Cabrio", ["modelname"] = "NINEF2",["rarity"] = 8 },
	[25] = { ["name"] = "Cavalcade", ["modelname"] = "Cavalcade",["rarity"] = 1 },
	[26] = { ["name"] = "Comet", ["modelname"] = "Comet2",["rarity"] = 12 },
	[27] = { ["name"] = "Rapid GT", ["modelname"] = "rapidgt",["rarity"] = 1 },
	[28] = { ["name"] = "Blista Compact", ["modelname"] = "blista2",["rarity"] = 1 },
	[29] = { ["name"] = "Mesa", ["modelname"] = "Mesa",["rarity"] = 6 },
	[31] = { ["name"] = "Banshee", ["modelname"] = "Banshee",["rarity"] = 15 },
	[32] = { ["name"] = "Carbonizzare", ["modelname"] = "carbonizzare",["rarity"] = 14 },
	[33] = { ["name"] = "Peyote", ["modelname"] = "Peyote",["rarity"] = 1 },
	[34] = { ["name"] = "BeeJay XL", ["modelname"] = "BJXL",["rarity"] = 5 },
	[35] = { ["name"] = "Dilettante", ["modelname"] = "Dilettante",["rarity"] = 1 },
	[36] = { ["name"] = "Tornado", ["modelname"] = "Tornado",["rarity"] = 1 },
	[37] = { ["name"] = "Rocoto", ["modelname"] = "Rocoto",["rarity"] = 1 },
	[38] = { ["name"] = "Zion", ["modelname"] = "Zion",["rarity"] = 11 },
	[39] = { ["name"] = "Furore", ["modelname"] = "FuroreGT",["rarity"] = 1 },
	[40] = { ["name"] = "Buffalo", ["modelname"] = "Buffalo",["rarity"] = 1 },
	[41] = { ["name"] = "F620", ["modelname"] = "F620",["rarity"] = 1 },
	[42] = { ["name"] = "Asea", ["modelname"] = "Asea",["rarity"] = 1 },
	[43] = { ["name"] = "Feltzer", ["modelname"] = "feltzer2",["rarity"] = 1 },
	[44] = { ["name"] = "Dubsta", ["modelname"] = "Dubsta",["rarity"] = 10 },
	[45] = { ["name"] = "FQ2", ["modelname"] = "FQ2",["rarity"] = 1 },
	[46] = { ["name"] = "Radius", ["modelname"] = "RADI",["rarity"] = 1 },
	[47] = { ["name"] = "Stanier", ["modelname"] = "Stanier",["rarity"] = 3 },
	[48] = { ["name"] = "Futo", ["modelname"] = "Futo",["rarity"] = 2 },
	[49] = { ["name"] = "Vigero", ["modelname"] = "Vigero",["rarity"] = 4 },
	[50] = { ["name"] = "Oracle", ["modelname"] = "oracle",["rarity"] = 3 },
	--[[[51] = { ["name"] = "Nine F", ["modelname"] = "ninef" },
	[52] = { ["name"] = "Banshee", ["modelname"] = "banshee" },
	[53] = { ["name"] = "Buffalo", ["modelname"] = "buffalo" },
	[54] = { ["name"] = "Fusilade", ["modelname"] = "fusilade" },
	[55] = { ["name"] = "Jester", ["modelname"] = "jester" },
	[56] = { ["name"] = "Kuruma", ["modelname"] = "kuruma" },
	[57] = { ["name"] = "Sultan", ["modelname"] = "sultan" },
	[58] = { ["name"] = "Infernus", ["modelname"] = "infernus" },
	[59] = { ["name"] = "Buccaneer", ["modelname"] = "buccaneer" },
	[6] = { ["name"] = "Chino", ["modelname"] = "chino" },
	[6] = { ["name"] = "Sanchez", ["modelname"] = "sanchez" },
	[6] = { ["name"] = "Dominator", ["modelname"] = "dominator" },
	[6] = { ["name"] = "Picador", ["modelname"] = "picador" },
	[6] = { ["name"] = "Bifta", ["modelname"] = "bifta" },
	[6] = { ["name"] = "Sandking", ["modelname"] = "sandking" },
	[6] = { ["name"] = "Bison", ["modelname"] = "bison" },
	[6] = { ["name"] = "Fugitive", ["modelname"] = "fugitive" },
	[6] = { ["name"] = "Intruder", ["modelname"] = "intruder" },
	[6] = { ["name"] = "Premier", ["modelname"] = "premier" },
	[1] = { ["name"] = "Primo", ["modelname"] = "primo" },
	[1] = { ["name"] = "Regina", ["modelname"] = "regina" },
	[1] = { ["name"] = "Washington", ["modelname"] = "washington" },
	[1] = { ["name"] = "Akuma", ["modelname"] = "AKUMA" },
	[1] = { ["name"] = "Bagger", ["modelname"] = "bagger" },
	[1] = { ["name"] = "Bati", ["modelname"] = "bati" },
	[1] = { ["name"] = "Double", ["modelname"] = "double" },
	[1] = { ["name"] = "Hexer", ["modelname"] = "hexer" },
	[1] = { ["name"] = "Nemesis", ["modelname"] = "nemesis" },
	[1] = { ["name"] = "BF 400", ["modelname"] = "bf400" },
	[1] = { ["name"] = "Blade", ["modelname"] = "blade" },
	[1] = { ["name"] = "Hot Rod Blazer", ["modelname"] = "blazer3" },
	[1] = { ["name"] = "Street Blazer", ["modelname"] = "blazer4" },
	[1] = { ["name"] = "Buccaneer Custom", ["modelname"] = "buccaneer2" },
	[1] = { ["name"] = "Carbon RS", ["modelname"] = "carbonrs" },
	[1] = { ["name"] = "Cheburek", ["modelname"] = "cheburek" },
	[1] = { ["name"] = "Chino Custom", ["modelname"] = "chino2" },
	[1] = { ["name"] = "Cliffhanger", ["modelname"] = "cliffhanger" },
	[1] = { ["name"] = "Cognoscenti Cabrio", ["modelname"] = "cogcabrio" },
	[1] = { ["name"] = "Defiler", ["modelname"] = "defiler" },
	[1] = { ["name"] = "Diabolus", ["modelname"] = "diablous" },
	[1] = { ["name"] = "Diabolus Custom", ["modelname"] = "diablous2" },
	[1] = { ["name"] = "Ellie", ["modelname"] = "ellie" },
	[1] = { ["name"] = "Enduro", ["modelname"] = "enduro" },
	[1] = { ["name"] = "Esskey", ["modelname"] = "esskey" },
	[1] = { ["name"] = "Faction", ["modelname"] = "faction" },
	[1] = { ["name"] = "Faction Custom", ["modelname"] = "faction2" },
	[1] = { ["name"] = "Fagaloa", ["modelname"] = "fagaloa" },
	[1] = { ["name"] = "Faggio", ["modelname"] = "faggio" },
	[1] = { ["name"] = "Furore GT", ["modelname"] = "furoregt" },
	[1] = { ["name"] = "GB200", ["modelname"] = "gb200" },
	[1] = { ["name"] = "Kamacho", ["modelname"] = "kamacho" },
	[1] = { ["name"] = "Lynx", ["modelname"] = "lynx" },
	[1] = { ["name"] = "Manchez", ["modelname"] = "manchez" },
	[1] = { ["name"] = "Nightblade", ["modelname"] = "nightblade" },
	[1] = { ["name"] = "Primo Custom", ["modelname"] = "primo2" },
	[1] = { ["name"] = "Raiden", ["modelname"] = "raiden" },
	[1] = { ["name"] = "Rapid GT Classic", ["modelname"] = "rapidgt3" },
	[1] = { ["name"] = "Sadler", ["modelname"] = "sadler" },
	[1] = { ["name"] = "Schafter LWB", ["modelname"] = "schafter4" },
	[1] = { ["name"] = "Sentinel Classic", ["modelname"] = "sentinel3" },
	[1] = { ["name"] = "Sovereign", ["modelname"] = "sovereign" },
	[1] = { ["name"] = "Clown Van", ["modelname"] = "speedo2" },
	[1] = { ["name"] = "Stryder", ["modelname"] = "stryder" },
	[1] = { ["name"] = "Toros", ["modelname"] = "toros" },
	[1] = { ["name"] = "Tropos Rallye", ["modelname"] = "tropos" },
	[1] = { ["name"] = "Vindicator", ["modelname"] = "vindicator" },
	[1] = { ["name"] = "Voodoo", ["modelname"] = "voodoo" },
	[1] = { ["name"] = "Windsor", ["modelname"] = "windsor" },
	[1] = { ["name"] = "Windsor Drop", ["modelname"] = "windsor2" }]]
}
