INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES
	('diamante', 'Diamond', 1, 0, 1),
	('diamond', 'Diamond', 1, 0, 1),
	('esmeralda', 'Emerald', 1, 0, 1),
	('fonesmineiro', 'Protection Headphones', 1, 0, 1),
	('gold', 'Gold', 1, 0, 1),
	('maquina', 'Machine', 1, 0, 1),
	('oculosmineiro', 'Protective Glasses', 1, 0, 1),
	('ouro', 'Gold', 1, 0, 1),
	('pedraspartidas', 'Broken Stones', 1, 0, 1),
	('picaretalevel1', 'Pickaxes Lvl 1', 1, 0, 1),
	('picaretalevel2', 'Pickaxes Lvl 2', 1, 0, 1),
	('picaretalevel3', 'Pickaxes Lvl 3', 1, 0, 1),
	('picaretalevel4', 'Pickaxes Lvl 4', 1, 0, 1),
	('picaretalevel5', 'Pickaxes Lvl 5', 1, 0, 1),
	('safira', 'Sapphire', 1, 0, 1),
	('stone', 'Stone', 1, 0, 1),
	('titanite', 'Titanite', 1, 0, 1),
	('wolframite', 'Wolframite', 1, 0, 1),
	('pedras', 'Stones', 1, 0, 1),
;
