INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES
	('anchor', 'Anchor', 1, 0, 1),
	('atum', 'Tuna fish', 1, 0, 1),
	('bacalhau', 'Cod', 1, 0, 1),
	('bacalhaucozido', 'Cooked Cod', 1, 0, 1),
	('baleia', 'Whale', 1, 0, 1),
	('cananivel1', 'Fishingrod Nivel 1', 1, 0, 1),
	('cananivel2', 'Fishingrod Nivel 2', 1, 0, 1),
	('cananivel3', 'Fishingrod Nivel 3', 1, 0, 1),
	('cananivel4', 'Fishingrod Nivel 4', 1, 0, 1),
	('cananivel5', 'Fishingrod Nivel 5', 1, 0, 1),
	('fishbait', 'Fish Bait', 1, 0, 1),
	('fishbaitilegal', 'Fish Bait Ilegal', 1, 0, 1),
	('fishingboot', 'Fishing Boot', 1, 0, 1),
	('fishingkey', 'Corroded Key', 1, 0, 1),
	('fishingloot', 'Metal Box', 1, 0, 1),
	('fishinglootbig', 'Treasure Chest', 1, 0, 1),
	('fishingtin', 'Fishing Tin', 1, 0, 1),
	('fogueira', 'Campfire', 1, 0, 1),
	('golfinho', 'Dolphin', 1, 0, 1),
	('linguado', 'Sole', 1, 0, 1),
	('peixegato', 'Catfish', 1, 0, 1),
	('raia', 'Stingray', 1, 0, 1),
	('rededepescanivel1', 'Fishing net Nivel 1', 1, 0, 1),
	('rededepescanivel2', 'Fishing net Nivel 2', 1, 0, 1),
	('rededepescanivel3', 'Fishing net Nivel 3', 1, 0, 1),
	('rededepescanivel4', 'Fishing net Nivel 4', 1, 0, 1),
	('rededepescanivel5', 'Fishing net Nivel 5', 1, 0, 1),
	('robalo', 'Sea Bass', 1, 0, 1),
	('salmao', 'Salmon', 1, 0, 1),
	('salmaocozido', 'Cooked Salmon', 1, 0, 1),
	('sardinha', 'Sardine', 1, 0, 1),
	('sardinhacozida', 'Cooked Sardines', 1, 0, 1),
	('tamboril', 'Monkfish', 1, 0, 1),
	('tubaraomartelo', 'Hammer shark', 1, 0, 1),
	('tubaraotigre', 'Tiger shark', 1, 0, 1)
;